#!/usr/bin/env python3
"""
qblast variant builder.

For each cfg in a JSON list, copies the kernel source into a per-variant tmp
directory, stamps the cfg's tunable parameters into qblast_variant_config.h,
runs `make tree` there, and collects the resulting skel .so files.

Usage:
    qblast-env                                          # source SDK env first
    scripts/variant_builder.py \\
        --kernel gemv_w4a16 \\
        --cfg-file scripts/database/cfgs/sample.json \\
        --output-dir scripts/database/variants/

Each cfg JSON object is:
    {"cfg_id": 0, "q_block": 64, "tile_m": 1, "n_hw_threads": 1}
keys map to QBLAST_<KEY_UPPER> defines in qblast_variant_config.h.

Why per-variant tmp copies? The Hexagon SDK Makefile system aggregates flags
inside a python telematics wrapper that swallows our `EXTRA_CFLAGS=...`
attempts; trying to drive the SDK rules.min `<NAME>_C_FLAGS` lookup also
turned out to be brittle (the wrapper's stdout doesn't even surface the
real hexagon-clang command). Generating a per-variant include header is
robust because it doesn't depend on any Makefile cooperation -- the kernel
source file `#include`s it unconditionally.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


def cfg_to_defines(cfg: dict) -> tuple[str, dict[str, int]]:
    """(variant_tag, {QBLAST_KEY: value}) for one cfg."""
    cfg_id = cfg["cfg_id"]
    defines: dict[str, int] = {}
    for key, value in cfg.items():
        if key == "cfg_id":
            continue
        macro = "QBLAST_" + key.upper()
        defines[macro] = value
    return f"v{cfg_id}", defines


def render_variant_config_h(defines: dict[str, int]) -> str:
    """Renders qblast_variant_config.h text for one cfg."""
    lines = [
        "// AUTO-GENERATED by variant_builder.py — do not edit.",
        "// This is a per-variant tmp copy; the committed source-dir version",
        "// holds the default baseline values.",
        "",
        "#ifndef QBLAST_VARIANT_CONFIG_H",
        "#define QBLAST_VARIANT_CONFIG_H",
        "",
    ]
    for macro, value in defines.items():
        lines.append(f"#define {macro:<25} {value}")
    lines.extend(["", "#endif  // QBLAST_VARIANT_CONFIG_H", ""])
    return "\n".join(lines)


def build_one(src_kernel_dir: Path, variant_tag: str, defines: dict[str, int],
              dsp_variant: str, log_file: Path) -> Path:
    """Build one variant in a fresh tmp source copy. Returns path to the .so."""
    env = os.environ.copy()
    if "HEXAGON_SDK_ROOT" not in env:
        sys.exit("[variant_builder] ERROR: HEXAGON_SDK_ROOT not set; run qblast-env first.")
    if "SDK_SETUP_ENV" not in env:
        sys.exit("[variant_builder] ERROR: SDK_SETUP_ENV not set; run qblast-env first.")

    # tempfile.mkdtemp gives a unique dir; we'll copy source into it.
    tmp_root = Path(tempfile.mkdtemp(prefix=f"qblast_{variant_tag}_"))
    work_kernel = tmp_root / src_kernel_dir.name
    # The kernel source `#include`s ../common/fp16_compat.h, so we need to
    # mirror that two-level layout under tmp_root.
    common_src = src_kernel_dir.parent / "common"
    if common_src.is_dir():
        shutil.copytree(common_src, tmp_root / "common")
    shutil.copytree(src_kernel_dir, work_kernel)

    # Stamp the per-variant header.
    variant_header = work_kernel / "qblast_variant_config.h"
    variant_header.write_text(render_variant_config_h(defines))

    # Use a unique target DLL name so the produced .so is self-identifying
    # and won't collide if we later push multiple to /data/local/tmp/.
    cmd = [
        "make",
        f"V={dsp_variant}",
        f"VARIANT={variant_tag}",
        "tree",
    ]
    print(f"[variant_builder] cd {work_kernel} && {' '.join(cmd)}")

    with open(log_file, "w") as lf:
        lf.write(f"# variant_tag={variant_tag}\n# defines={defines}\n# tmp={work_kernel}\n\n")
        lf.flush()
        proc = subprocess.run(cmd, cwd=work_kernel, env=env,
                              stdout=lf, stderr=subprocess.STDOUT)
    if proc.returncode != 0:
        sys.exit(f"[variant_builder] make failed for {variant_tag}; see {log_file} (kept tmp at {work_kernel})")

    if variant_tag == "default":
        so_name = f"lib{src_kernel_dir.name}_skel.so"
    else:
        so_name = f"lib{src_kernel_dir.name}_{variant_tag}_skel.so"

    candidates = [
        work_kernel / dsp_variant / "ship" / so_name,
        work_kernel / dsp_variant / so_name,
    ]
    so_path = next((p for p in candidates if p.exists()), None)
    if so_path is None:
        sys.exit(f"[variant_builder] expected {so_name} not produced under {work_kernel}/{dsp_variant}/")

    # Stash a copy outside the tmp dir before we may clean tmp; return that.
    return so_path


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--kernel", required=True,
                    help="kernel name; matches src/kernels/hexagon/<kernel>/")
    ap.add_argument("--cfg-file", required=True, type=Path)
    ap.add_argument("--variant", default="hexagon_Release_toolv19_v81",
                    help="DSP build variant (default: v81 Release)")
    ap.add_argument("--output-dir", required=True, type=Path,
                    help="where to copy collected skel .so files")
    ap.add_argument("--repo-root", type=Path, default=None,
                    help="qblast repo root; defaults to script dir's parent")
    args = ap.parse_args()

    repo_root = (args.repo_root or Path(__file__).resolve().parent.parent).resolve()
    kernel_dir = (repo_root / "src" / "kernels" / "hexagon" / args.kernel).resolve()
    if not kernel_dir.is_dir():
        sys.exit(f"[variant_builder] kernel dir not found: {kernel_dir}")

    cfgs = json.loads(args.cfg_file.read_text())
    if not isinstance(cfgs, list):
        sys.exit(f"[variant_builder] {args.cfg_file} must contain a JSON list")

    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    log_dir = output_dir / "build_logs"
    log_dir.mkdir(exist_ok=True)

    built: list[dict] = []
    for cfg in cfgs:
        variant_tag, defines = cfg_to_defines(cfg)
        log_file = log_dir / f"{variant_tag}.log"
        so_path = build_one(kernel_dir, variant_tag, defines, args.variant, log_file)
        dest = output_dir / so_path.name
        shutil.copy2(so_path, dest)
        built.append({
            "cfg_id": cfg["cfg_id"],
            "variant_tag": variant_tag,
            "defines": defines,
            "so": str(dest.relative_to(repo_root)),
        })
        print(f"[variant_builder]   -> {dest.relative_to(repo_root)}")

    manifest = output_dir / "manifest.json"
    manifest.write_text(json.dumps(built, indent=2) + "\n")
    print(f"[variant_builder] wrote {manifest.relative_to(repo_root)} ({len(built)} variants)")


if __name__ == "__main__":
    main()
